# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Generate NuGet 
      run: dotnet build
    - name: Publish NuGet to nuget.org
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json
    - name: Add GitHub as source
      run: dotnet nuget add source --username hunterlan --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/hunterlan/VirusTotalCore/index.json"
    - name: Publish NuGet to GitHub
      run: dotnet nuget push "*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
